CREATE TABLE IF NOT EXISTS #__openchart_msg(
	id INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	user_id INT(10) NOT NULL,
	msg TEXT,
	datetime timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS #__openchart_blocked_users(
	id INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	user_id INT(10) NOT NULL,
	datetime timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);